create table IF NOT EXISTS qualification
(
    id   integer generated by default as identity
        primary key,
    name varchar(255)
);


INSERT INTO qualification (name)
VALUES
    ('Advanced HTML/CSS'),
    ('5 years in PHP'),
    ('3+ years in Angular'),
    ('2 years in Vue.js'),
    ('Expert in JavaScript'),
    ('Skilled in React'),
    ('Proficient in Kotlin'),
    ('Proficient in SQL'),
    ('3 years in Node.js'),
    ('Solid understanding of AWS'),
    ('Skilled in GraphQL'),
    ('Proficient in MongoDB'),
    ('3+ years in Python'),
    ('2 years of Git experience'),
    ('Master of TypeScript'),
    ('2+ years in Ruby'),
    ('4+ years in C++'),
    ('Expert in Docker'),
    ('Expert in Java'),
    ('Advanced in Swift');