version: "3"
services:
  webapp:
    build: webapp
    container_name: web-app
    ports:
      - "3000:3000"
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: applicant
  backend:
    build: ./backend
    container_name: backend-service
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - db

